[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.5"
utils = { path = "../utils" }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
strip = true
