[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", default-features = false, features = [
    "blocking",
] }
utils = { path = "../utils" }
mimalloc = "0.1.43"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
strip = true
