[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
lz4_flex = { version = "0.11.3", default-features = false }
actix-web = "4"
zstd = "0.13.2"
utils = { path = "../utils" }


[profile.release]
panic = "abort"
codegen-units = 1
lto = true
strip = true
